apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-site-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: html-site
  template:
    metadata:
      labels:
        app: html-site
    spec:
      containers:
      - name: html-site
        image: shilu07/html-site:latest
        ports:
        - containerPort: 80
